name: boilerplate
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  cloud_firestore: ^5.6.5
  google_fonts: ^6.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  email_validator: ^3.0.0
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.5.2
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

 

